services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        #REQUIRED
        HOST: ${HOST}
        PORT: ${PORT:-3000}

        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
        NEXT_PUBLIC_MARKETING_URL: ${NEXT_PUBLIC_MARKETING_URL}
        POSTGRES_PRISMA_URL: ${POSTGRES_PRISMA_URL}
        POSTGRES_PRISMA_URL_NON_POOLING: ${POSTGRES_PRISMA_URL_NON_POOLING}
        BLOB_READ_WRITE_TOKEN: ${BLOB_READ_WRITE_TOKEN}
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

        #RESEND
        RESEND_API_KEY: ${RESEND_API_KEY}
        RESEND_EMAIL: ${RESEND_EMAIL}

        #TINYBIRD
        TINYBIRD_TOKEN: ${TINYBIRD_TOKEN}

        #QTASH
        QSTASH_TOKEN: ${QSTASH_TOKEN}
        QSTASH_CURRENT_SIGNING_KEY: ${QSTASH_CURRENT_SIGNING_KEY}
        QSTASH_NEXT_SIGNING_KEY: ${QSTASH_NEXT_SIGNING_KEY}
        #HANKO
        HANKO_API_KEY: ${HANKO_API_KEY}
        NEXT_PUBLIC_HANKO_TENANT_ID: ${NEXT_PUBLIC_HANKO_TENANT_ID}

        #TRIGGER V3
        TRIGGER_SECRET_KEY: ${TRIGGER_SECRET_KEY}
        TRIGGER_API_URL: ${TRIGGER_API_URL}
        
        #STORAGE
        NEXT_PUBLIC_UPLOAD_TRANSPORT: ${NEXT_PUBLIC_UPLOAD_TRANSPORT}
        NEXT_PRIVATE_UPLOAD_DISTRIBUTION_HOST: ${NEXT_PRIVATE_UPLOAD_DISTRIBUTION_HOST}
        NEXT_PRIVATE_UPLOAD_ENDPOINT: ${NEXT_PRIVATE_UPLOAD_ENDPOINT}
        NEXT_PRIVATE_UPLOAD_REGION: ${NEXT_PRIVATE_UPLOAD_REGION}
        NEXT_PRIVATE_UPLOAD_BUCKET: ${NEXT_PRIVATE_UPLOAD_BUCKET}
        NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID: ${NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID}
        NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY: ${NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY}
        NEXT_PRIVATE_UPLOAD_DISTRIBUTION_DOMAIN: ${NEXT_PRIVATE_UPLOAD_DISTRIBUTION_DOMAIN}
        NEXT_PRIVATE_UPLOAD_DISTRIBUTION_KEY_ID: ${NEXT_PRIVATE_UPLOAD_DISTRIBUTION_KEY_ID}
        NEXT_PRIVATE_UPLOAD_DISTRIBUTION_KEY_CONTENTS: ${NEXT_PRIVATE_UPLOAD_DISTRIBUTION_KEY_CONTENTS}

        NEXT_PRIVATE_DOCUMENT_PASSWORD_KEY: ${NEXT_PRIVATE_DOCUMENT_PASSWORD_KEY}
        #REDIS
        UPSTASH_REDIS_REST_LOCKER_URL: ${UPSTASH_REDIS_REST_LOCKER_URL}
        UPSTASH_REDIS_REST_LOCKER_TOKEN: ${UPSTASH_REDIS_REST_LOCKER_TOKEN}

        #OPENAI
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ${NEXT_PUBLIC_STRIPE_PUBLIC_KEY}
        STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}

        #VERIFICATION
        NEXT_PRIVATE_VERIFICATION_SECRET: ${NEXT_PRIVATE_VERIFICATION_SECRET}

        #WEBHOOKS
        NEXT_PUBLIC_WEBHOOK_BASE_URL: ${NEXT_PUBLIC_WEBHOOK_BASE_URL}
        NEXT_PUBLIC_WEBHOOK_BASE_HOST: ${NEXT_PUBLIC_WEBHOOK_BASE_HOST}
    ports:
      - '${PORT:-3000}'
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true
